import {NextResponse} from 'next/server'
import {enrichProjectWithCountyGis} from '@/lib/gis'
export const runtime='nodejs'
export const maxDuration=300

const schema={type:'object',additionalProperties:false,required:['project','timeline','documents','traffic','reviewNotes'],properties:{
project:{type:'object',additionalProperties:false,required:['name','slug','county','caseNumber','parcelIds','status','homesProposed','siteAcres','buildableAcres','developer','engineer','summary','latestUpdateDate','latestUpdate','nextStep'],properties:{name:{type:'string'},slug:{type:'string'},county:{type:'string'},caseNumber:{type:'string'},parcelIds:{type:'array',items:{type:'string'}},status:{type:'string'},homesProposed:{type:'number'},siteAcres:{type:'number'},buildableAcres:{type:'number'},developer:{type:'string'},engineer:{type:'string'},summary:{type:'string'},latestUpdateDate:{type:'string'},latestUpdate:{type:'string'},nextStep:{type:'string'}}},
timeline:{type:'array',items:{type:'object',additionalProperties:false,required:['title','date','stageStatus','description','sourceDocument'],properties:{title:{type:'string'},date:{type:'string'},stageStatus:{type:'string',enum:['complete','current','future']},description:{type:'string'},sourceDocument:{type:'string'}}}},
documents:{type:'array',items:{type:'object',additionalProperties:false,required:['title','category','date','sourceName','sourceUrl','filename'],properties:{title:{type:'string'},category:{type:'string'},date:{type:'string'},sourceName:{type:'string'},sourceUrl:{type:'string'},filename:{type:'string'}}}},
traffic:{type:'object',additionalProperties:false,required:['tiaDate','trafficEngineer','dailyTrips','amPeakTrips','pmPeakTrips','buildOutYear','accessRoads','improvements','notes'],properties:{tiaDate:{type:'string'},trafficEngineer:{type:'string'},dailyTrips:{type:'number'},amPeakTrips:{type:'number'},pmPeakTrips:{type:'number'},buildOutYear:{type:'number'},accessRoads:{type:'array',items:{type:'string'}},improvements:{type:'array',items:{type:'string'}},notes:{type:'string'}}},
reviewNotes:{type:'array',items:{type:'string'}}}}

function outputText(x:any){if(typeof x?.output_text==='string')return x.output_text;for(const i of x?.output||[])for(const c of i?.content||[])if(c?.type==='output_text')return c.text;throw new Error('No structured output returned.')}
async function upload(file:File,key:string){const form=new FormData();form.set('purpose','user_data');form.set('file',file);form.set('expires_after[anchor]','created_at');form.set('expires_after[seconds]','86400');const r=await fetch('https://api.openai.com/v1/files',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form});if(!r.ok)throw new Error(`Upload failed for ${file.name}: ${await r.text()}`);return r.json()}
async function stage(pkg:any,names:string[]){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;const r=await fetch(`${url.replace(/\/$/,'')}/rest/v1/cfdt_import_jobs`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({status:'review',source_files:names,extracted_package:pkg})});if(!r.ok)throw new Error(`Supabase staging failed: ${await r.text()}`);const rows=await r.json();return rows?.[0]?.id||null}

export async function POST(req:Request){try{const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:'OPENAI_API_KEY is missing.'},{status:500});const form=await req.formData();const files=form.getAll('files').filter((x):x is File=>x instanceof File);if(!files.length)return NextResponse.json({error:'Choose at least one PDF.'},{status:400});if(files.length>5)return NextResponse.json({error:'Use no more than five PDFs.'},{status:400});for(const f of files)if(f.size>20*1024*1024)return NextResponse.json({error:`${f.name} exceeds 20 MB.`},{status:400});const ids=[];for(const f of files){const u=await upload(f,key);ids.push({id:u.id,name:f.name})}const content:any[]=[{type:'input_text',text:'Extract a factual CFDT development package from the attached official planning records. Extract every explicitly printed parcel ID or PIN into project.parcelIds without changing its spelling. Use only supported facts. Use empty strings, empty arrays, or 0 when unknown. Do not invent dates, approvals, acreage, homes, traffic counts, parcel IDs, or next steps. Put conflicts and uncertainty in reviewNotes. Mark only dated verified milestones complete and the most recent verified milestone current.'},...ids.map(f=>({type:'input_file',file_id:f.id,filename:f.name,detail:'high'}))];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_EXTRACTION_MODEL||'gpt-5-mini',input:[{role:'user',content}],text:{format:{type:'json_schema',name:'cfdt_project_package',strict:true,schema}}})});if(!r.ok)return NextResponse.json({error:`OpenAI extraction failed: ${await r.text()}`},{status:502});const raw=await r.json();const parsed=JSON.parse(outputText(raw));const project=await enrichProjectWithCountyGis(parsed.project);const extracted={...parsed,project};const jobId=await stage(extracted,files.map(f=>f.name));return NextResponse.json({ok:true,jobId,extracted,model:raw.model,responseId:raw.id})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Extraction failed.'},{status:500})}}
